# Generated by Django 2.2.25 on 2021-12-24 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_software_technical'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subtitle',
            field=models.TextField(blank=True, null=True, verbose_name='サブタイトル'),
        ),
    ]
