# Generated by Django 2.2.25 on 2021-12-25 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211224_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papername', models.TextField(verbose_name='論文名')),
                ('authorname', models.TextField(verbose_name='著者名')),
                ('confname', models.TextField(verbose_name='会議名')),
            ],
        ),
    ]
