# Generated by Django 2.2.25 on 2021-12-26 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_scholarship'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='資格名')),
                ('period', models.CharField(max_length=100, verbose_name='取得日')),
            ],
        ),
    ]
